/*
 * To change this license header, choose License Headers   in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jls.Kun;

import ADT.LList;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import jdk.nashorn.internal.ir.BreakNode;
import jls.Customer;
import jls.HomePage;
import jls.Order;
import jls.Product;
import jls.Purchase;

/**
 *
 * @author Yee Kun
 */
public class SelectItem_CorCust extends javax.swing.JFrame {

    LList<Product> ProductList = new LList<>();
    LList<Customer> CustList = new LList<>();
    LList<Order> OrderList = new LList<>();
    Purchase homepage;
    SelectItem selectitem;
    GridBagLayout layout = new GridBagLayout();
    Fresh p1;
    Bouquet p2;

    /**
     * Creates new form SelectItem_CorCust
     */
    public SelectItem_CorCust(LList<Product> ProductList, LList<Customer> CustList, LList<Order> OrderList, Purchase homepage) {
        this.ProductList = ProductList;
        this.CustList = CustList;
        this.OrderList = OrderList;
        this.homepage = homepage;
        initComponents();
        rdFresh.setSelected(true);
        p1 = new Fresh(ProductList);
        p2 = new Bouquet(ProductList);
        jPanel1.setLayout(layout);
        GridBagConstraints c = new GridBagConstraints();
        c.gridx = 150;
        c.gridy = 0;
        jPanel1.add(p1, c);
        c.gridx = 0;
        c.gridy = 0;
        jPanel1.add(p2, c);
        p1.setVisible(true);
        p2.setVisible(false);
        showName();
    }

    public void showName() {
        for (int i = 1; i < CustList.getNumberOfEntries(); i++) {
            if (homepage.jTextField1.getText().equals(CustList.getEntry(i).getIc())) {
                jLabel3.setText(CustList.getEntry(i).getName());
                lblCreditLimit.setText(Integer.toString(CustList.getEntry(i).getRemaincredit()));
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        rdFresh = new javax.swing.JRadioButton();
        rdBouquet = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblCreditLimit = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lblTotalPrice = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Corporate Customer Select Item and Quantity");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Flore FlowerShop");

        buttonGroup1.add(rdFresh);
        rdFresh.setText("Fresh Flowers");
        rdFresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdFreshActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdBouquet);
        rdBouquet.setText("Bouquest");
        rdBouquet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdBouquetActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Name: ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Ramaining Credit Limit (RM): ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 297, Short.MAX_VALUE)
        );

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Total Price (RM): ");

        lblTotalPrice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTotalPrice.setText("0");

        jButton1.setText("Reset");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Calculate Price");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Place Order");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(93, 93, 93)
                .addComponent(lblTotalPrice)
                .addGap(82, 82, 82))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(129, 129, 129)
                .addComponent(jButton2)
                .addGap(139, 139, 139)
                .addComponent(jButton3)
                .addGap(91, 91, 91))
            .addGroup(layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(87, 87, 87))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(rdFresh)
                        .addGap(20, 20, 20)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCreditLimit)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(rdBouquet)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(lblCreditLimit)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdBouquet)
                    .addComponent(rdFresh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblTotalPrice))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jButton3)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        boolean order = false;
        int qty = 0;
        int total = 0;

        for (int i = 0; i < p1.jTable1.getRowCount(); i++) {
            p1.jTable1.setValueAt(order, i, 1);
            p1.jTable1.setValueAt(qty, i, 3);
            p1.jTable1.setValueAt(total, i, 4);
        }

        for (int i = 0; i < p2.jTable1.getRowCount(); i++) {
            p2.jTable1.setValueAt(order, i, 1);
            p2.jTable1.setValueAt(qty, i, 3);
            p2.jTable1.setValueAt(total, i, 4);
        }

        lblTotalPrice.setText("0");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int totalPrice = 0;

        for (int i = 0; i < p1.jTable1.getRowCount(); i++) {
            boolean p1chkOrder = (boolean) p1.jTable1.getValueAt(i, 1);
            int p1qty = Integer.parseInt(p1.jTable1.getValueAt(i, 3).toString());
            int p1price = Integer.parseInt(p1.jTable1.getValueAt(i, 2).toString());
            String empty = "0";

            if (p1chkOrder == true && p1qty < 1) {
                JOptionPane.showMessageDialog(rootPane, "Quantity cannot less than or equal 0.", "Warning", JOptionPane.INFORMATION_MESSAGE);
                break;
            } else if (p1chkOrder == true && p1qty > 0) {
                int total = p1price * p1qty;
                p1.jTable1.setValueAt(total, i, 4);
                totalPrice += total;
                lblTotalPrice.setText(Integer.toString(totalPrice));
            } else if (p1chkOrder == false && p1qty > 0) {
                p1.jTable1.setValueAt(empty, i, 4);
            }

        }

        for (int i = 0; i < p2.jTable1.getRowCount(); i++) {
            boolean p2chkOrder = (boolean) p2.jTable1.getValueAt(i, 1);
            int p2qty = Integer.parseInt(p2.jTable1.getValueAt(i, 3).toString());
            int p2price = Integer.parseInt(p2.jTable1.getValueAt(i, 2).toString());
            String empty = "0";

            if (p2chkOrder == true && p2qty < 1) {
                JOptionPane.showMessageDialog(rootPane, "Quantity cannot less than or equal 0.", "Warning", JOptionPane.INFORMATION_MESSAGE);
                break;
            } else if (p2chkOrder == true && p2qty > 0) {
                int total = p2price * p2qty;
                p2.jTable1.setValueAt(total, i, 4);
                totalPrice += total;
                lblTotalPrice.setText(Integer.toString(totalPrice));
            } else if (p2chkOrder == false && p2qty > 0) {
                p2.jTable1.setValueAt(empty, i, 4);
            }

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        DefaultTableModel model = (DefaultTableModel) p1.jTable1.getModel();
        boolean error = false;
        int totalPrice = 0;
        int CreditLimit = Integer.parseInt(lblCreditLimit.getText().toString());

        for (int i = 0; i < p1.jTable1.getRowCount(); i++) {
            boolean p1chkOrder = (boolean) p1.jTable1.getValueAt(i, 1);
            int p1chkQty = Integer.parseInt(p1.jTable1.getValueAt(i, 3).toString());
            int p1price = Integer.parseInt(p1.jTable1.getValueAt(i, 2).toString());

            if (p1chkOrder == true && p1chkQty < 1) {
                error = true;
                break;
            } else if (p1chkOrder == true && p1chkQty > 0) {
                int total = p1price * p1chkQty;
                totalPrice += total;

            }
        }

        for (int k = 0; k < p2.jTable1.getRowCount(); k++) {
            boolean p2chkOrder = (boolean) p2.jTable1.getValueAt(k, 1);
            int p2chkQty = Integer.parseInt(p2.jTable1.getValueAt(k, 3).toString());
            int p2price = Integer.parseInt(p2.jTable1.getValueAt(k, 2).toString());

            if (p2chkOrder == true && p2chkQty < 1) {
                error = true;
                break;
            } else if (p2chkOrder == true && p2chkQty > 0) {
                int total = p2price * p2chkQty;
                totalPrice += total;
            }
        }

        if (error == true) {
            JOptionPane.showMessageDialog(rootPane, "Quantity cannot less than or equal 0.", "Warning", JOptionPane.INFORMATION_MESSAGE);
        } else if (totalPrice > CreditLimit) {
            JOptionPane.showMessageDialog(rootPane, "The Monthly Credit Limit no enough.", "Warning", JOptionPane.INFORMATION_MESSAGE);
        } else {
            int select = JOptionPane.showConfirmDialog(rootPane, "Confirm Order??", "Process to select pick-up priority", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (select == 0) {
                
                int remainingcreditlimit = CreditLimit - totalPrice;

                for (int j = 1; j < CustList.getNumberOfEntries(); j++) {
                    if (CustList.getEntry(j).getName().equals(jLabel3.getText())) {
                        CustList.getEntry(j).setRemaincredit(remainingcreditlimit);
                    }
                }
                model.fireTableDataChanged();
                this.dispose();
                new ConfirmOrder(p1, p2, selectitem, CustList, OrderList, this, homepage, ProductList).setVisible(true);
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void rdFreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdFreshActionPerformed
        p1.setVisible(true);
        p2.setVisible(false);
    }//GEN-LAST:event_rdFreshActionPerformed

    private void rdBouquetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdBouquetActionPerformed
        p2.setVisible(true);
        p1.setVisible(false);
    }//GEN-LAST:event_rdBouquetActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCreditLimit;
    private javax.swing.JLabel lblTotalPrice;
    private javax.swing.JRadioButton rdBouquet;
    private javax.swing.JRadioButton rdFresh;
    // End of variables declaration//GEN-END:variables
}
