/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jls.Kun;

import ADT.LList;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import jls.Customer;
import jls.HomePage;
import jls.Order;
import jls.Product;

/**
 *
 * @author yeekun
 */
public class SelectItem extends javax.swing.JFrame {
    LList<Product> ProductList = new LList<>();
    LList<Customer> CustList = new LList<>();
    LList<Order> OrderList = new LList<>();
    HomePage homepage;
    SelectItem_CorCust selectItem_CorCust;
    GridBagLayout layout = new GridBagLayout();
    Fresh p1;
    Bouquet p2;
    /**
     * Creates new form SelectItem
     */
    public SelectItem(LList<Product> ProductList, LList<Customer> CustList, LList<Order> OrderList, HomePage homepage) {
        this.ProductList = ProductList;
        this.CustList = CustList;
        this.OrderList = OrderList;
        this.homepage = homepage;
        initComponents();
        rdFresh.setSelected(true);
        p1 = new Fresh(ProductList);
        p2 = new Bouquet(ProductList);
        jPanel.setLayout(layout);
        GridBagConstraints c = new GridBagConstraints();
        c.gridx = 150;
        c.gridy = 0;
        jPanel.add(p1, c);
        c.gridx = 0;
        c.gridy = 0;
        jPanel.add(p2, c);
        p1.setVisible(true);
        p2.setVisible(false);    
        showName();
    }
    
    public void showName(){
        for(int i=1; i<CustList.getNumberOfEntries(); i++){
            if(homepage.jTextField1.getText().equals(CustList.getEntry(i).getIc())){
                jLabel3.setText(CustList.getEntry(i).getName());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        buttonGroup1 = new javax.swing.ButtonGroup();
        lblShop = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();
        btnPlaceOrder = new javax.swing.JButton();
        btnCalculate = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblTotalPrice = new javax.swing.JLabel();
        jPanel = new javax.swing.JPanel();
        rdFresh = new javax.swing.JRadioButton();
        rdBouquet = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Select Items and Quantity");

        lblShop.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblShop.setText("Flore FlowerShop");

        btnReset.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnPlaceOrder.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPlaceOrder.setText("Place Order");
        btnPlaceOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlaceOrderActionPerformed(evt);
            }
        });

        btnCalculate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCalculate.setText("Calculate Price");
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Total Price (RM)");

        lblTotalPrice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTotalPrice.setText("0");

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 302, Short.MAX_VALUE)
        );

        buttonGroup1.add(rdFresh);
        rdFresh.setText("Fresh Flowers");
        rdFresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdFreshActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdBouquet);
        rdBouquet.setText("Bouquet");
        rdBouquet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdBouquetActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Name: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(93, 93, 93)
                .addComponent(lblTotalPrice)
                .addGap(83, 83, 83))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(btnReset)
                .addGap(129, 129, 129)
                .addComponent(btnCalculate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                .addComponent(btnPlaceOrder)
                .addGap(91, 91, 91))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(rdFresh)
                        .addGap(66, 66, 66)
                        .addComponent(rdBouquet))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(lblShop))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lblShop)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(rdBouquet))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rdFresh)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblTotalPrice))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPlaceOrder)
                    .addComponent(btnCalculate)
                    .addComponent(btnReset))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        boolean order = false;
        int qty = 0;
        int total = 0;
        
        for (int i = 0; i < p1.jTable1.getRowCount(); i++) {
            p1.jTable1.setValueAt(order, i, 1);
            p1.jTable1.setValueAt(qty, i, 3);
            p1.jTable1.setValueAt(total, i, 4);
        }
        
        for (int i = 0; i < p2.jTable1.getRowCount(); i++) {
            p2.jTable1.setValueAt(order, i, 1);
            p2.jTable1.setValueAt(qty, i, 3);
            p2.jTable1.setValueAt(total, i, 4);
        }
        
        lblTotalPrice.setText("0");
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
        int totalPrice = 0;
        
        for (int i = 0; i < p1.jTable1.getRowCount(); i++) {
            boolean p1chkOrder = (boolean) p1.jTable1.getValueAt(i, 1);
            int p1qty = Integer.parseInt(p1.jTable1.getValueAt(i, 3).toString());
            int p1price = Integer.parseInt(p1.jTable1.getValueAt(i, 2).toString());
            String empty = "0";
            

            if(p1chkOrder == true && p1qty < 1){
                JOptionPane.showMessageDialog(rootPane, "Quantity cannot less than or equal 0.", "Warning", JOptionPane.INFORMATION_MESSAGE);
                break;
            }
            else if(p1chkOrder == true && p1qty > 0){
                int total = Cal_subtotal(p1price, p1qty);
                p1.jTable1.setValueAt(total, i, 4);
                totalPrice += total;
                lblTotalPrice.setText(Integer.toString(totalPrice));
            }
            else if(p1chkOrder == false && p1qty > 0){
                p1.jTable1.setValueAt(empty, i, 4);
            }

        }
        
        for (int i = 0; i < p2.jTable1.getRowCount(); i++) {
            boolean p2chkOrder = (boolean) p2.jTable1.getValueAt(i, 1);
            int p2qty = Integer.parseInt(p2.jTable1.getValueAt(i, 3).toString());
            int p2price = Integer.parseInt(p2.jTable1.getValueAt(i, 2).toString());
            String empty = "0";
            

            if(p2chkOrder == true && p2qty < 1){
                JOptionPane.showMessageDialog(rootPane, "Quantity cannot less than or equal 0.", "Warning", JOptionPane.INFORMATION_MESSAGE);
                break;
            }
            else if(p2chkOrder == true && p2qty > 0){
                int total = p2price * p2qty;
                p2.jTable1.setValueAt(total, i, 4);
                totalPrice += total;
                lblTotalPrice.setText(Integer.toString(totalPrice));
            }
            else if(p2chkOrder == false && p2qty > 0){
                p2.jTable1.setValueAt(empty, i, 4);
            }

        }

       
    }//GEN-LAST:event_btnCalculateActionPerformed

    private void btnPlaceOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlaceOrderActionPerformed
        DefaultTableModel model = (DefaultTableModel) p1.jTable1.getModel();
        boolean error = false; 
        for (int i = 0; i < p1.jTable1.getRowCount(); i++) {
            boolean p1chkOrder = (boolean) p1.jTable1.getValueAt(i, 1);
            int p1chkQty = Integer.parseInt(p1.jTable1.getValueAt(i, 3).toString());

            if(p1chkOrder == true && p1chkQty < 1){
                error = true;     
                break;
            }                                                            
        }
        
        for (int k = 0; k < p2.jTable1.getRowCount(); k++) {
            boolean p2chkOrder = (boolean) p2.jTable1.getValueAt(k, 1);
            int p2chkQty = Integer.parseInt(p2.jTable1.getValueAt(k, 3).toString());
            
            if(p2chkOrder == true && p2chkQty < 1){
                error = true;     
                break;
            }  
        }     
        
        if(error == true){
            JOptionPane.showMessageDialog(rootPane, "Quantity cannot less than or equal 0.", "Warning", JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            int select = JOptionPane.showConfirmDialog(rootPane, "Confirm Order??", "Process to select pick-up priority", JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
            if (select == 0){
                model.fireTableDataChanged();
                new ConfirmOrder(p1,p2, this, CustList, OrderList, selectItem_CorCust, homepage).setVisible(true);                                   
            }
        }     
        
    }//GEN-LAST:event_btnPlaceOrderActionPerformed

    private void rdBouquetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdBouquetActionPerformed
        p2.setVisible(true);
        p1.setVisible(false);
    }//GEN-LAST:event_rdBouquetActionPerformed

    private void rdFreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdFreshActionPerformed
        p1.setVisible(true);
        p2.setVisible(false);
    }//GEN-LAST:event_rdFreshActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculate;
    private javax.swing.JButton btnPlaceOrder;
    private javax.swing.JButton btnReset;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblShop;
    private javax.swing.JLabel lblTotalPrice;
    private javax.swing.JRadioButton rdBouquet;
    private javax.swing.JRadioButton rdFresh;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables

    public int Cal_subtotal(int p1price, int p1qty) {
        int temp = p1price * p1qty;
        return temp;
    }
}
