/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jls.CusOrder;

import java.awt.List;
import java.util.ArrayList;
import javax.swing.JTable;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author user
 */
public class Table extends javax.swing.JFrame {

    private DefaultTableModel model;
    private DefaultTableModel model1;
    String id;
    String lvl;
    int e;
    /**
     * Creates new form Priority_Table
     */
    public Table() {
        initComponents();
    }
    
     public Table(String Priority) {
        initComponents();
       JTable table = new JTable(model);
       Object[] column = { "ItemID","Priority"};
        model = new DefaultTableModel();
      model.setColumnIdentifiers(column);
        jTable1.setModel(model);
        Object [][] data =   {{ "I001",  "Express"},
                { "I002",  "Express"},
                { "I003",  "Normal"},
                { "I004",  "Flexi"},
        };
        model.setDataVector(data, column);
        for (int i =0; i<=data.length;i++){
          id = "I" + String.format("%03d", (i+1));
      }
        Object[] row = new Object[2];
        row[0] = id;
        row[1] = Priority;
        
        model.addRow(row);
        
       JTable table1 = new JTable(model1);
       Object[] column1 = { "ItemID","Priority"};
        model1 = new DefaultTableModel();
      model1.setColumnIdentifiers(column1);
        jTable1.setModel(model1);
        
        Object[] express= new Object[2];
        Object[] Normal= new Object[2];
         Object[] Flexi= new Object[2];
        for (int i =0; i<=data.length;i++){
          id = (String)model.getValueAt(i, 0);
          lvl = (String)model.getValueAt(i, 1);
          if(lvl =="Express"){
               
               express[0] = id;
               express[1] = lvl;
               model1.addRow(express);
                e++;
            }
        }
       for (int o =0; o<=data.length;o++){
          id = (String)model.getValueAt(o, 0);
          lvl = (String)model.getValueAt(o, 1);
          if(lvl == "Normal"){
               Normal[0] = id;
               Normal[1] = lvl; 
                model1.addRow(Normal);
          }
       }
        for (int p =0; p<=data.length;p++){
          id = (String)model.getValueAt(p, 0);
          lvl = (String)model.getValueAt(p, 1);
          
        if(lvl == "Flexi"){
              
               Flexi[0] = id;
               Flexi[1] = lvl;
             model1.addRow(Flexi);
          }
          }
        
         
       
      sort();

    }
 public void sort(){
     
     TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<DefaultTableModel>(model);
     jTable1.setRowSorter(sorter);
 }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Priority Table", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 14))); // NOI18N

//        jTable1.setModel(new javax.swing.table.DefaultTableModel(
//            new Object [][] {
//                { "I001",  "High"},
//                { "I002",  "High"},
//                { "I003",  "Low"}
//            },
//            new String [] {
//                "ItemID","Priority"
//            }
//        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel1.setText("Delivery Priority ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Priority_Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Priority_Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Priority_Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Priority_Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Priority_Table().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration                   
}
