/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jls.Sushi;

import ADT.LList;
import ADT.SListInterface;
import javax.swing.table.DefaultTableModel;
import jls.Order;
import java.util.ArrayList;
import java.util.List;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import jls.Arrangement;
import jls.Customer;
import jls.Product;

/**
 *
 * @author Sushi
 */
public class PickUp extends javax.swing.JPanel {
    LList<Order> OrderList;
    SListInterface<Arrangement> ArrangeList;
    LList<Customer> CustList ;
    LList<Product> ProductList;
    /**
     * Creates new form PickUp
     */
    public PickUp(LList<Order> OrderList, SListInterface<Arrangement> ArrangeList,LList<Customer> CustList ,LList<Product> ProductList) {
        initComponents();
        this.OrderList = OrderList;
        this.ArrangeList = ArrangeList;
        this.CustList = CustList;
        this.ProductList = ProductList;
        addRowToJTable();
    }

    public void addRowToJTable(){
    DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
    
    Object rowData[] = new Object[5];
        
        for(int i=1; i<=OrderList.getNumberOfEntries(); i++){
            if(!OrderList.getEntry(i).getPickup_date().equals("Delivery") && !OrderList.getEntry(i).getPickup_time().equals("Delivery")){
            rowData[0] = OrderList.getEntry(i).getOrder_ID();
            rowData[1] = OrderList.getEntry(i).getCust_name();
//            rowData[2] = OrderList.getEntry(i).getItem_name();
            rowData[2] = OrderList.getEntry(i).getPickup_time();
            rowData[3] = OrderList.getEntry(i).getPickup_date();
            rowData[4] = OrderList.getEntry(i).getStatus();

            model.addRow(rowData);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(550, 180));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "OrderID", "CustName", "Time", "Date", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        //TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(jTable2.getModel());
        //            jTable2.setRowSorter(sorter);
        //
        //            List<RowSorter.SortKey> sortKeys = new ArrayList<>(25);
        //            sortKeys.add(new RowSorter.SortKey(4, SortOrder.ASCENDING));
        //            sorter.setSortKeys(sortKeys);
        jScrollPane2.setViewportView(jTable2);

        jButton2.setText("Edit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jButton2)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(jTable2.getSelectedRow() != -1){
            new EditOrder(jTable2.getModel(),jTable2.getSelectedRow(), OrderList).setVisible(true);
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
