/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.jyjyjhfjf
 */
package jls.Hawman;

import javax.swing.ButtonModel;
import javax.swing.JOptionPane;

/**
 *
 * @author hawma
 */
public class ModifyProductInfo extends javax.swing.JFrame {
    ModifyProductInfo2 p1;
    /**
     * Creates new form ModifyProductInfo
     */
    public ModifyProductInfo() {
        initComponents();
        p1 = new ModifyProductInfo2(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Modify Product Information");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("Fresh flower");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Rose");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Lily");

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Chrysanthemum");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setText("Bouquet");

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("Rose bouquet");

        buttonGroup1.add(jRadioButton5);
        jRadioButton5.setText("Lily bouquet");

        buttonGroup1.add(jRadioButton6);
        jRadioButton6.setText("Chrysanthemum bouquet");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setText("Floral arrangement accesory");

        buttonGroup1.add(jRadioButton7);
        jRadioButton7.setText("Teddy bear");

        buttonGroup1.add(jRadioButton8);
        jRadioButton8.setText("Heart balloon");

        jButton1.setText("Modify");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Select an item below to modify:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jButton1)
                    .addComponent(jRadioButton8)
                    .addComponent(jRadioButton7)
                    .addComponent(jLabel4)
                    .addComponent(jRadioButton6)
                    .addComponent(jRadioButton5)
                    .addComponent(jRadioButton4)
                    .addComponent(jLabel3)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton3)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton6)
                .addGap(28, 28, 28)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton8)
                .addGap(45, 45, 45)
                .addComponent(jButton1)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (buttonGroup1.getSelection() != null) {
            p1.setVisible(true);
        }
        else {
            JOptionPane.showMessageDialog(rootPane, "Please select an item.");
        }
        
        if (jRadioButton1.isSelected() == true) {
            p1.jTextField1.setText("Rose");
            p1.jTextArea1.setText("Beautiful rose.");
            p1.jTextField2.setText("6.20");
            p1.jTextField3.setText("17");
        }
        else if (jRadioButton2.isSelected() == true) {
            p1.jTextField1.setText("Lily");
            p1.jTextArea1.setText("Beautiful lily.");
            p1.jTextField2.setText("6.20");
            p1.jTextField3.setText("17");
        }
        else if (jRadioButton3.isSelected() == true) {
            p1.jTextField1.setText("Chrysanthemum");
            p1.jTextArea1.setText("Beautiful chrysanthemum.");
            p1.jTextField2.setText("6.20");
            p1.jTextField3.setText("17");
        }
        else if (jRadioButton4.isSelected() == true) {
            p1.jTextField1.setText("Rose bouquet");
            p1.jTextArea1.setText("Beautiful rose bouquet.");
            p1.jTextField2.setText("6.20");
            p1.jTextField3.setText("17");
        }
        else if (jRadioButton5.isSelected() == true) {
            p1.jTextField1.setText("Lily bouquet");
            p1.jTextArea1.setText("Beautiful lily bouquet.");
            p1.jTextField2.setText("6.20");
            p1.jTextField3.setText("17");
        }
        else if (jRadioButton6.isSelected() == true) {
            p1.jTextField1.setText("Chrysanthemum bouquet");
            p1.jTextArea1.setText("Beautiful chrysanthemum bouquet.");
            p1.jTextField2.setText("6.20");
            p1.jTextField3.setText("17");
        }
        else if (jRadioButton7.isSelected() == true) {
            p1.jTextField1.setText("Teddy bear");
            p1.jTextArea1.setText("Nice cute teddy bear.");
            p1.jTextField2.setText("6.20");
            p1.jTextField3.setText("17");
        }
        else if (jRadioButton8.isSelected() == true) {
            p1.jTextField1.setText("Heart balloon");
            p1.jTextArea1.setText("Lovely balloon.");
            p1.jTextField2.setText("6.20");
            p1.jTextField3.setText("17");
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModifyProductInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModifyProductInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModifyProductInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModifyProductInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModifyProductInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public javax.swing.JRadioButton jRadioButton1;
    public javax.swing.JRadioButton jRadioButton2;
    public javax.swing.JRadioButton jRadioButton3;
    public javax.swing.JRadioButton jRadioButton4;
    public javax.swing.JRadioButton jRadioButton5;
    public javax.swing.JRadioButton jRadioButton6;
    public javax.swing.JRadioButton jRadioButton7;
    public javax.swing.JRadioButton jRadioButton8;
    // End of variables declaration//GEN-END:variables
}
